source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'SwiftyExts_Example' do
  
#  pod 'SwiftyExts', :subspecs => ['All'], :path => '../'
  pod 'SwiftyExts/Device', :path => '../'
#pod 'SwiftyExts/Device'
#pod 'SwiftyExts/Reachability'
#pod 'SwiftyExts/Attributes'

  target 'SwiftyExts_Tests' do
    inherit! :search_paths

    
  end
end
